name: Node.js Automated 4-Stage Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-stage:
    name: 2.1 Build Stage
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: echo "Building application artifact..."

  test-stage:
    name: 2.2 Test Stage
    needs: build-stage
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Test
        run: npm test

  release-stage:
    name: 2.3 Release Stage
    needs: test-stage
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t node-app:latest .
          echo "Release Artifact (Docker Image) Created."

deploy-stage:
    name: 2.4 Deploy Stage
    needs: release-stage
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy to Environment
        run: |
          docker-compose down --remove-orphans || true
          docker rm -f mysql-db express-backend || true
          docker-compose up -d
          echo "Application Deployed Successfully via Docker Compose."
